export const TECH_JOKES = [
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "I would tell you a UDP joke, but you might not get it.",
    "There are 10 types of people in the world: those who understand binary, and those who don't.",
    "My code doesn't work, I have no idea why. My code works, I have no idea why.",
    "A SQL query walks into a bar, walks up to two tables and asks... 'Can I join you?'",
    "How many programmers does it take to change a light bulb? None, that's a hardware problem.",
    "Why was the JavaScript developer sad? Because he didn't know how to 'null' his feelings.",
    "Debugging: Being the detective in a crime movie where you are also the murderer.",
    "Why did the edge server go bankrupt? Because it lost its cache.",
    "Git happened.",
    "A CSS developer walks into a bar and immediately starts crying because the layout is absolute.",
    "['hip', 'hip'] (hip hip array!)",
    "Why did the functional programmer get thrown out of the library? He was creating side effects.",
    "A byte walks into a bar and says, 'I'd like a drink.' Bartender: 'Are you sure?' Byte: 'Yes, I'm feeling a bit parity.'",
    "Hardware is the part of the computer you can kick; software is the part you can only curse at.",
    "To understand recursion, you must first understand recursion.",
    "Why do Java programmers wear glasses? Because they don't C#.",
    "Why was the mobile developer so broke? Because he spent all his cache on a new thread.",
    "Keyboard not found. Press F1 to continue.",
    "A programmer's wife: 'Go to the store and buy a loaf of bread. If they have eggs, get a dozen.' He comes home with 12 loaves.",
    "There's no place like 127.0.0.1.",
    "What’s the object-oriented way to become wealthy? Inheritance.",
    "Why did the DBA leave his wife? She had too many foreign keys.",
    "!false (It's funny because it's true.)",
    "An SEO expert walks into a bar, bars, pub, tavern, public house, Irish pub, drinks, beer, wine...",
    "I would love to tell you a joke about DNS, but it might take 24 hours to resolve.",
    "Why do programmers always mix up Halloween and Christmas? Because Oct 31 == Dec 25.",
    "Documentation is like sex. When it's good, it's very good. When it's bad, it's better than nothing.",
    "A programmer had a problem. He thought, 'I know, I'll use regex.' Now he has two problems.",
    "Why did the computer show up late to work? It had a hard drive.",
    "Why was the developer so cold? He was sitting near the Windows.",
    "What do you call a programmer from Finland? Nerdic.",
    "Why did the Python programmer get bit? He forgot to close his brackets... oh wait.",
    "Unix is user-friendly. It's just very picky about who its friends are.",
    "How do you comfort a JavaScript bug? You console it.",
    "Why did the pointer go to the party? It wanted to see what was at that address.",
    "I've got a great joke about 404, but I can't find it.",
    "A user interface is like a joke. If you have to explain it, it’s not that good.",
    "What’s a pirate's favorite programming language? You’d think it’s R, but his first love is the C.",
    "Why are Assembly programmers always so stressed? They have too many registers to manage.",
    "What do you call a computer that sings? A Dell.",
    "Why did the developer stay at the office all night? He couldn't find the exit code.",
    "Life is too short for long compile times.",
    "What do you call a group of 8 Hobbits? A Hobbyte.",
    "How many developers does it take to screw in a lightbulb? None, they just define darkness as a standard.",
    "A programmer puts two glasses on his nightstand: one full of water in case he's thirsty, and one empty in case he's not.",
    "Why did the Node.js developer feel lonely? Because he was trapped in callback hell.",
    "What is the most used language in programming? Profanity.",
    "Why did the CSS file go to therapy? It had too many internal conflicts.",
    "If you listen closely, you can hear the fans of a laptop crying when you open 40 Chrome tabs.",
    "Why did the API break up with the client? There was no chemistry, just bad requests.",
    "Why did the developer bring a ladder to the server room? Because the cloud was too high.",
    "Machine Learning is just statistics with better marketing.",
    "Artificial intelligence is no match for natural stupidity.",
    "Why do programmers hate nature? It has too many bugs and the lighting is inconsistent.",
    "Knock, knock. (Who's there?) ... (very long pause) ... Java.",
    "How does a programmer get out of a burning building? They use the firewall.",
    "My code is like a recipe. One wrong ingredient and the whole thing crashes the kitchen.",
    "Why did the database administrator get kicked out of the party? He kept trying to join tables.",
    "What's a programmer's favorite snack? Micro-chips.",
    "Why did the developer quit his job? He didn't get arrays.",
    "The glass is not half full or half empty; it’s twice as big as the requirements specified.",
    "Why did the thread go to the doctor? It had a race condition.",
    "Why was the computer so good at golf? It had a great swing (Java).",
    "I have a joke about Kubernetes, but I'll need a few more nodes to tell it.",
    "Why did the React developer take a nap? Because they were tired of state management.",
    "A QA engineer walks into a bar. Orders a beer. Orders 0 beers. Orders 99999999999 beers. Orders a lizard. Orders -1 beers. Orders a ueicbksjdne.",
    "There are two ways to write error-free programs; only the third one works.",
    "Why did the computer get a ticket? It was speeding through the bus.",
    "C++: Where you have to manage your own garbage, unlike Java where the garbage collector follows you.",
    "Why did the developer go to the gym? To improve his core logic.",
    "If at first you don't succeed, call it version 1.0.",
    "Why did the web designer leave the restaurant? They didn't like the table layout.",
    "Why was the script so good at comedy? It had perfect timing.",
    "What happens when a programmer gets an inheritance? They usually just get a bunch of properties.",
    "Why do programmers prefer cats? Because cats also have an 'ignore' function.",
    "Why did the computer go to school? To improve its processing power.",
    "What's the best way to catch a tech-savvy thief? Use a firewall.",
    "My code doesn't have bugs, it just has unintended features.",
    "How do you tell an introverted programmer from an extroverted one? The extroverted one looks at *your* shoes when he talks to you."
];