// import { tool } from "langchain";
// import { z } from "zod";
// import { workflow } from "./workflow";

// export const searchKnowledgeBase = tool(
//     async ({ query }) => {
//         const result = await workflow.invoke({ query });
//         return result.finalAnswer;
//     },
//     {
//         name: "search_knowledge_base",
//         description: `Primary knowledge and reasoning engine for this system.

//             This tool executes the complete multi-agent workflow, including:
//             - Topic filtering
//             - Safety and guardrails enforcement
//             - AI Twin reasoning and retrieval
//             - Stateful conversation handling with memory

//             MANDATORY USAGE:
//             - You MUST call this tool for EVERY user query.
//             - Do NOT answer from your own knowledge.
//             - Do NOT generate responses without calling this tool.
//             - This tool is the single source of truth for all answers.

//             Input should always be the full user query.
//             Returns the final conversational response generated by the system.`,
//         schema: z.object({
//             query: z.string().describe("The search query"),
//         }),
//     }
// );